[meta]
title = "Subesokuns personal~ radar"
categories = [ "Tools", "Techniques", "Platforms", "Frameworks" ]
states = [ "Novice", "Intermediate", "Advanced", "Veteran" ]

[[blips]]
category = 3
title = "Go"
state = 0

  [[blips.changes]]
  date = "2018-12"
  newState = 0
  text = "Solving Advent-Of-Code puzzles in Go"
